// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"moj/question/db"
	"moj/question/domain"
	"moj/question/etc"
	"moj/question/svc"
	"moj/domain/question"
)

// Injectors from wire.go:

func InitializeApplication() *App {
	config := etc.NewAppConfig()
	mongoDB := db.NewMongoDB(config)
	questionRepository := domain.NewMongoDBQuestionRepository(mongoDB)
	createQuestionCmdHandler := question.NewCreateQuestionCmdHandler(questionRepository)
	modifyQuestionCmdHandler := question.NewModifyQuestionCmdHandler(questionRepository)
	questionDao := db.NewMongoDBQuestionDAO(mongoDB)
	server := svc.NewServer(createQuestionCmdHandler, modifyQuestionCmdHandler, questionDao, questionRepository)
	app := NewApp(server, mongoDB, config)
	return app
}

// wire.go:

var providers = wire.NewSet(svc.NewServer, question.NewCreateQuestionCmdHandler, question.NewModifyQuestionCmdHandler, domain.NewMongoDBQuestionRepository, db.NewMongoDBQuestionDAO, etc.NewAppConfig, db.NewMongoDB)
