// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"moj/apps/game/db"
	"moj/apps/game/domain"
	"moj/apps/game/etc"
	"moj/apps/game/listener"
	"moj/apps/game/mq"
	"moj/apps/game/svc"
	"moj/domain/game"
)

// Injectors from wire.go:

func InitializeApplication() *App {
	config := etc.NewAppConfig()
	mongoDB := db.NewMongoDB(config)
	gameViewDao := db.NewMongoDBGameViewDao(mongoDB)
	signUpScoreDao := db.NewMongoDBSignUpScoreDao(mongoDB)
	transactionManager := db.NewMongoDBTransactionManager(mongoDB)
	eventDispatcher := provideDispatcher(signUpScoreDao)
	commandInvoker := domain.NewTransactionCommandInvoker(transactionManager, eventDispatcher)
	gameRepository := domain.NewMongoDBGameRepository(mongoDB)
	createGameCmdHandler := game.NewCreateGameCmdHandler(gameRepository)
	modifyGameCmdHandler := game.NewModifyGameCmdHandler(gameRepository)
	signupGameCmdHandler := game.NewSignUpGameCmdHandler(gameRepository)
	cancelSignUpGameCmdHandler := game.NewCancelSignUpGameCmdHandler(gameRepository)
	server := svc.NewServer(gameViewDao, signUpScoreDao, commandInvoker, gameRepository, createGameCmdHandler, modifyGameCmdHandler, signupGameCmdHandler, cancelSignUpGameCmdHandler)
	calculateScoreCmdHandler := game.NewCalculateScoreCmdHandler(gameRepository)
	nsqCalculateScoreConsumer := mq.NewNsqCalculateScoreConsumer(config, calculateScoreCmdHandler, eventDispatcher)
	app := NewApp(server, mongoDB, config, nsqCalculateScoreConsumer)
	return app
}

// wire.go:

func provideDispatcher(supDao db.SignUpScoreDao) domain.EventDispatcher {
	return domain.NewSyncEventDispatcher(listener.NewSignUpScoreLisener(supDao))
}

var providers = wire.NewSet(svc.NewServer, game.NewSignUpGameCmdHandler, game.NewCancelSignUpGameCmdHandler, game.NewCreateGameCmdHandler, game.NewModifyGameCmdHandler, game.NewCalculateScoreCmdHandler, mq.NewNsqCalculateScoreConsumer, provideDispatcher, domain.NewSimpleEventQueue, domain.NewTransactionCommandInvoker, domain.NewMongoDBGameRepository, db.NewMongoDBTransactionManager, db.NewMongoDBSignUpScoreDao, db.NewMongoDBGameViewDao, db.NewMongoDB, etc.NewAppConfig)
