// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type CursorPage interface {
	IsCursorPage()
	GetNextID() string
}

type OffsetPage interface {
	IsOffsetPage()
	GetTotal() int
}

type Case struct {
	Number         int    `json:"number"`
	InputFilePath  string `json:"inputFilePath"`
	OutputFilePath string `json:"outputFilePath"`
}

type CaseInput struct {
	Number         int    `json:"number"`
	InputFilePath  string `json:"inputFilePath"`
	OutputFilePath string `json:"outputFilePath"`
}

type ChangePasswordInput struct {
	ID          string `json:"id"`
	NewPassword string `json:"newPassword"`
	Captcha     string `json:"captcha"`
}

type DailyTasksNumber struct {
	SumbitNumber int `json:"sumbitNumber"`
	FinishNumber int `json:"finishNumber"`
}

type FinishedQuestion struct {
	EazyCount   int `json:"eazyCount"`
	NormalCount int `json:"normalCount"`
	HardCount   int `json:"hardCount"`
}

type Game struct {
	ID           string          `json:"id"`
	CreaterID    string          `json:"createrID"`
	Title        string          `json:"title"`
	Description  string          `json:"description"`
	StartTime    string          `json:"startTime"`
	EndTime      string          `json:"endTime"`
	CreateTime   string          `json:"createTime"`
	QuestionList []*GameQuestion `json:"questionList"`
}

type GameInput struct {
	ID           *string              `json:"id,omitempty"`
	Title        string               `json:"title"`
	Description  string               `json:"description"`
	StartTime    string               `json:"startTime"`
	EndTime      string               `json:"endTime"`
	QuestionList []*GameQuestionInput `json:"questionList"`
}

type GamePage struct {
	NextID string  `json:"nextID"`
	Games  []*Game `json:"games"`
}

func (GamePage) IsCursorPage()          {}
func (this GamePage) GetNextID() string { return this.NextID }

type GameQuestion struct {
	QuestionID string `json:"questionID"`
	Score      int    `json:"score"`
}

type GameQuestionInput struct {
	QuestionID string `json:"questionID"`
	Score      int    `json:"score"`
}

type GamesFilter struct {
	Word *string `json:"word,omitempty"`
	Time *string `json:"time,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResult struct {
	Token *Token `json:"token"`
	User  *User  `json:"user"`
}

type Mutation struct {
}

type Query struct {
}

type Question struct {
	ID               string             `json:"id"`
	CreaterID        string             `json:"createrID"`
	Enabled          bool               `json:"enabled"`
	Title            string             `json:"title"`
	Content          string             `json:"content"`
	Level            Level              `json:"level"`
	AllowedLanguages []string           `json:"allowedLanguages"`
	TimeLimit        int                `json:"timeLimit"`
	MemoryLimit      int                `json:"memoryLimit"`
	Tags             []string           `json:"tags"`
	CreateTime       string             `json:"createTime"`
	ModifyTime       string             `json:"modifyTime"`
	Cases            []*Case            `json:"cases"`
	PassStatus       QuestionPassStatus `json:"passStatus"`
}

type QuestionInput struct {
	ID               *string      `json:"id,omitempty"`
	Title            string       `json:"title"`
	Enabled          bool         `json:"enabled"`
	Content          string       `json:"content"`
	Level            Level        `json:"level"`
	AllowedLanguages []string     `json:"allowedLanguages"`
	TimeLimit        int          `json:"timeLimit"`
	MemoryLimit      int          `json:"memoryLimit"`
	Tags             []string     `json:"tags"`
	Cases            []*CaseInput `json:"cases"`
}

type QuestionPage struct {
	NextID    string      `json:"nextID"`
	Questions []*Question `json:"questions"`
}

func (QuestionPage) IsCursorPage()          {}
func (this QuestionPage) GetNextID() string { return this.NextID }

type QuestionsFilter struct {
	Word      *string `json:"word,omitempty"`
	Enabled   *bool   `json:"enabled,omitempty"`
	Level     *Level  `json:"level,omitempty"`
	Language  *string `json:"language,omitempty"`
	CreaterID *string `json:"createrID,omitempty"`
}

type Record struct {
	ID               string  `json:"id"`
	UserID           string  `json:"userID"`
	QuestionID       string  `json:"questionID"`
	GameID           *string `json:"gameID,omitempty"`
	Language         string  `json:"language"`
	Code             string  `json:"code"`
	CodeHash         string  `json:"codeHash"`
	JudgeStatus      string  `json:"judgeStatus"`
	FailedReason     string  `json:"failedReason"`
	NumberFinishedAt int     `json:"numberFinishedAt"`
	TotalCase        int     `json:"totalCase"`
	CreateTime       string  `json:"createTime"`
	FinishTime       string  `json:"finishTime"`
	MemoryUsed       int     `json:"memoryUsed"`
	TimeUserd        int     `json:"timeUserd"`
	CPUTimeUsed      int     `json:"cpuTimeUsed"`
}

type RecordPage struct {
	Records []*Record `json:"records"`
	Total   int       `json:"total"`
}

func (RecordPage) IsOffsetPage()      {}
func (this RecordPage) GetTotal() int { return this.Total }

type RegisterInput struct {
	NickName string `json:"nickName"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Captcha  string `json:"captcha"`
}

type Score struct {
	UserID     string `json:"userID"`
	Score      int    `json:"score"`
	SignUpTime string `json:"signUpTime"`
}

type ScoresPage struct {
	Total  int      `json:"total"`
	Scores []*Score `json:"scores"`
}

func (ScoresPage) IsOffsetPage()      {}
func (this ScoresPage) GetTotal() int { return this.Total }

type SendChangePasswordEmail struct {
	UserID string `json:"userID"`
	Email  string `json:"email"`
}

type SendRegisterEmail struct {
	Email string `json:"email"`
}

type SubmitCount struct {
	SubmitCount int `json:"submitCount"`
	PassedCount int `json:"passedCount"`
}

type Time struct {
	Time string `json:"time"`
}

type Token struct {
	RefreshToken string `json:"refreshToken"`
	AccessToken  string `json:"accessToken"`
}

type User struct {
	ID                   string            `json:"id"`
	Email                string            `json:"email"`
	AvatarLink           string            `json:"avatarLink"`
	NickName             string            `json:"nickName"`
	Enabled              bool              `json:"enabled"`
	IsAdmin              bool              `json:"isAdmin"`
	LastLoginTime        string            `json:"lastLoginTime"`
	LastLoginIPAddr      string            `json:"lastLoginIPAddr"`
	LastLoginDevice      string            `json:"lastLoginDevice"`
	LastPasswdChangeTime string            `json:"lastPasswdChangeTime"`
	RegisterTime         string            `json:"registerTime"`
	DeleteTime           string            `json:"deleteTime"`
	FinishedQuestion     *FinishedQuestion `json:"finishedQuestion"`
}

type UserInfo struct {
	ID         string `json:"id"`
	NickName   string `json:"nickName"`
	AvatarLink string `json:"avatarLink"`
}

type UserPage struct {
	Users  []*User `json:"users"`
	NextID string  `json:"nextID"`
}

func (UserPage) IsCursorPage()          {}
func (this UserPage) GetNextID() string { return this.NextID }

type UsersFilter struct {
	Enabled *bool   `json:"enabled,omitempty"`
	IsAdmin *bool   `json:"isAdmin,omitempty"`
	Word    *string `json:"word,omitempty"`
}

type Level string

const (
	LevelEazy   Level = "Eazy"
	LevelNormal Level = "Normal"
	LevelHard   Level = "Hard"
)

var AllLevel = []Level{
	LevelEazy,
	LevelNormal,
	LevelHard,
}

func (e Level) IsValid() bool {
	switch e {
	case LevelEazy, LevelNormal, LevelHard:
		return true
	}
	return false
}

func (e Level) String() string {
	return string(e)
}

func (e *Level) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Level(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Level", str)
	}
	return nil
}

func (e Level) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type QuestionPassStatus string

const (
	QuestionPassStatusUndo    QuestionPassStatus = "Undo"
	QuestionPassStatusWorking QuestionPassStatus = "Working"
	QuestionPassStatusPass    QuestionPassStatus = "Pass"
)

var AllQuestionPassStatus = []QuestionPassStatus{
	QuestionPassStatusUndo,
	QuestionPassStatusWorking,
	QuestionPassStatusPass,
}

func (e QuestionPassStatus) IsValid() bool {
	switch e {
	case QuestionPassStatusUndo, QuestionPassStatusWorking, QuestionPassStatusPass:
		return true
	}
	return false
}

func (e QuestionPassStatus) String() string {
	return string(e)
}

func (e *QuestionPassStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = QuestionPassStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid QuestionPassStatus", str)
	}
	return nil
}

func (e QuestionPassStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
