// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: rpc/sb-judger.proto

package sb_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_c      Language = 0
	Language_cpp    Language = 1
	Language_golang Language = 2
	Language_java   Language = 3
	Language_python Language = 4
	Language_rust   Language = 5
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "c",
		1: "cpp",
		2: "golang",
		3: "java",
		4: "python",
		5: "rust",
	}
	Language_value = map[string]int32{
		"c":      0,
		"cpp":    1,
		"golang": 2,
		"java":   3,
		"python": 4,
		"rust":   5,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_sb_judger_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_rpc_sb_judger_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_rpc_sb_judger_proto_rawDescGZIP(), []int{0}
}

type State int32

const (
	State_CE  State = 0
	State_AC  State = 1
	State_WA  State = 2
	State_RE  State = 3
	State_TLE State = 4
	State_MLE State = 5
	State_UE  State = 6
)

// Enum value maps for State.
var (
	State_name = map[int32]string{
		0: "CE",
		1: "AC",
		2: "WA",
		3: "RE",
		4: "TLE",
		5: "MLE",
		6: "UE",
	}
	State_value = map[string]int32{
		"CE":  0,
		"AC":  1,
		"WA":  2,
		"RE":  3,
		"TLE": 4,
		"MLE": 5,
		"UE":  6,
	}
)

func (x State) Enum() *State {
	p := new(State)
	*p = x
	return p
}

func (x State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (State) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_sb_judger_proto_enumTypes[1].Descriptor()
}

func (State) Type() protoreflect.EnumType {
	return &file_rpc_sb_judger_proto_enumTypes[1]
}

func (x State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use State.Descriptor instead.
func (State) EnumDescriptor() ([]byte, []int) {
	return file_rpc_sb_judger_proto_rawDescGZIP(), []int{1}
}

type RunCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 编程语言
	Lang Language `protobuf:"varint,1,opt,name=lang,proto3,enum=v1.judger.Language" json:"lang,omitempty"`
	// 程序源代码
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// 程序输入内容
	Input string `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	// 限定运行时间(单位: ms [0, 2000])
	Time uint32 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	// 限定程序使用内存(单位: mb [1, 256])
	Memory uint32 `protobuf:"varint,5,opt,name=memory,proto3" json:"memory,omitempty"`
	// 限定输出内容大小(0 表示使用默认值，单位: kb)
	OutMsgLimit uint32 `protobuf:"varint,6,opt,name=out_msg_limit,json=outMsgLimit,proto3" json:"out_msg_limit,omitempty"`
}

func (x *RunCodeRequest) Reset() {
	*x = RunCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sb_judger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeRequest) ProtoMessage() {}

func (x *RunCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sb_judger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeRequest.ProtoReflect.Descriptor instead.
func (*RunCodeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_sb_judger_proto_rawDescGZIP(), []int{0}
}

func (x *RunCodeRequest) GetLang() Language {
	if x != nil {
		return x.Lang
	}
	return Language_c
}

func (x *RunCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RunCodeRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *RunCodeRequest) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *RunCodeRequest) GetMemory() uint32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *RunCodeRequest) GetOutMsgLimit() uint32 {
	if x != nil {
		return x.OutMsgLimit
	}
	return 0
}

type RunCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 程序输出
	OutPut string `protobuf:"bytes,1,opt,name=out_put,json=outPut,proto3" json:"out_put,omitempty"`
	// 程序运行Cpu耗时(ms)
	CpuTimeUsage float64 `protobuf:"fixed64,2,opt,name=cpu_time_usage,json=cpuTimeUsage,proto3" json:"cpu_time_usage,omitempty"`
	// 程序运行总耗时(ms)
	RealTimeUsage float64 `protobuf:"fixed64,3,opt,name=real_time_usage,json=realTimeUsage,proto3" json:"real_time_usage,omitempty"`
	// 程序使用内存(kb)
	MemoryUsage float64 `protobuf:"fixed64,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	// 程序运行状态
	State State `protobuf:"varint,5,opt,name=state,proto3,enum=v1.judger.State" json:"state,omitempty"`
}

func (x *RunCodeResponse) Reset() {
	*x = RunCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sb_judger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCodeResponse) ProtoMessage() {}

func (x *RunCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sb_judger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCodeResponse.ProtoReflect.Descriptor instead.
func (*RunCodeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_sb_judger_proto_rawDescGZIP(), []int{1}
}

func (x *RunCodeResponse) GetOutPut() string {
	if x != nil {
		return x.OutPut
	}
	return ""
}

func (x *RunCodeResponse) GetCpuTimeUsage() float64 {
	if x != nil {
		return x.CpuTimeUsage
	}
	return 0
}

func (x *RunCodeResponse) GetRealTimeUsage() float64 {
	if x != nil {
		return x.RealTimeUsage
	}
	return 0
}

func (x *RunCodeResponse) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *RunCodeResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_CE
}

type CodeResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaseId uint32 `protobuf:"varint,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	// 程序运行Cpu耗时(ms)
	CpuTimeUsage float64 `protobuf:"fixed64,2,opt,name=cpu_time_usage,json=cpuTimeUsage,proto3" json:"cpu_time_usage,omitempty"`
	// 程序运行总耗时(ms)
	RealTimeUsage float64 `protobuf:"fixed64,3,opt,name=real_time_usage,json=realTimeUsage,proto3" json:"real_time_usage,omitempty"`
	// 程序使用内存(kb)
	MemoryUsage float64 `protobuf:"fixed64,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	State       State   `protobuf:"varint,5,opt,name=state,proto3,enum=v1.judger.State" json:"state,omitempty"`
}

func (x *CodeResult) Reset() {
	*x = CodeResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sb_judger_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeResult) ProtoMessage() {}

func (x *CodeResult) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sb_judger_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeResult.ProtoReflect.Descriptor instead.
func (*CodeResult) Descriptor() ([]byte, []int) {
	return file_rpc_sb_judger_proto_rawDescGZIP(), []int{2}
}

func (x *CodeResult) GetCaseId() uint32 {
	if x != nil {
		return x.CaseId
	}
	return 0
}

func (x *CodeResult) GetCpuTimeUsage() float64 {
	if x != nil {
		return x.CpuTimeUsage
	}
	return 0
}

func (x *CodeResult) GetRealTimeUsage() float64 {
	if x != nil {
		return x.RealTimeUsage
	}
	return 0
}

func (x *CodeResult) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *CodeResult) GetState() State {
	if x != nil {
		return x.State
	}
	return State_CE
}

type JudgeCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 编程语言
	Lang Language `protobuf:"varint,1,opt,name=lang,proto3,enum=v1.judger.Language" json:"lang,omitempty"`
	// 程序源代码
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// 限定运行时间(单位: ms)
	Time uint32 `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	// 限定程序使用内存(单位: mb)
	Memory uint32 `protobuf:"varint,4,opt,name=memory,proto3" json:"memory,omitempty"`
	// 限定输出内容大小(0 表示使用默认值, 单位: kb)
	OutMsgLimit uint32  `protobuf:"varint,5,opt,name=out_msg_limit,json=outMsgLimit,proto3" json:"out_msg_limit,omitempty"`
	Case        []*Case `protobuf:"bytes,6,rep,name=case,proto3" json:"case,omitempty"`
}

func (x *JudgeCodeRequest) Reset() {
	*x = JudgeCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sb_judger_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JudgeCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeCodeRequest) ProtoMessage() {}

func (x *JudgeCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sb_judger_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeCodeRequest.ProtoReflect.Descriptor instead.
func (*JudgeCodeRequest) Descriptor() ([]byte, []int) {
	return file_rpc_sb_judger_proto_rawDescGZIP(), []int{3}
}

func (x *JudgeCodeRequest) GetLang() Language {
	if x != nil {
		return x.Lang
	}
	return Language_c
}

func (x *JudgeCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *JudgeCodeRequest) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *JudgeCodeRequest) GetMemory() uint32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *JudgeCodeRequest) GetOutMsgLimit() uint32 {
	if x != nil {
		return x.OutMsgLimit
	}
	return 0
}

func (x *JudgeCodeRequest) GetCase() []*Case {
	if x != nil {
		return x.Case
	}
	return nil
}

type JudgeCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 程序状态
	State State `protobuf:"varint,1,opt,name=state,proto3,enum=v1.judger.State" json:"state,omitempty"`
	// 程序使用最大时间(ms)
	MaxTimeUsage float64 `protobuf:"fixed64,2,opt,name=max_time_usage,json=maxTimeUsage,proto3" json:"max_time_usage,omitempty"`
	// 程序使用最大内存(byte)
	MaxMemoryUsage float64       `protobuf:"fixed64,3,opt,name=max_memory_usage,json=maxMemoryUsage,proto3" json:"max_memory_usage,omitempty"`
	OutPut         string        `protobuf:"bytes,4,opt,name=out_put,json=outPut,proto3" json:"out_put,omitempty"`
	CodeResults    []*CodeResult `protobuf:"bytes,5,rep,name=code_results,json=codeResults,proto3" json:"code_results,omitempty"`
}

func (x *JudgeCodeResponse) Reset() {
	*x = JudgeCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sb_judger_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JudgeCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeCodeResponse) ProtoMessage() {}

func (x *JudgeCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sb_judger_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeCodeResponse.ProtoReflect.Descriptor instead.
func (*JudgeCodeResponse) Descriptor() ([]byte, []int) {
	return file_rpc_sb_judger_proto_rawDescGZIP(), []int{4}
}

func (x *JudgeCodeResponse) GetState() State {
	if x != nil {
		return x.State
	}
	return State_CE
}

func (x *JudgeCodeResponse) GetMaxTimeUsage() float64 {
	if x != nil {
		return x.MaxTimeUsage
	}
	return 0
}

func (x *JudgeCodeResponse) GetMaxMemoryUsage() float64 {
	if x != nil {
		return x.MaxMemoryUsage
	}
	return 0
}

func (x *JudgeCodeResponse) GetOutPut() string {
	if x != nil {
		return x.OutPut
	}
	return ""
}

func (x *JudgeCodeResponse) GetCodeResults() []*CodeResult {
	if x != nil {
		return x.CodeResults
	}
	return nil
}

type Case struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaseId uint32 `protobuf:"varint,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	In     string `protobuf:"bytes,2,opt,name=in,proto3" json:"in,omitempty"`
	Out    string `protobuf:"bytes,3,opt,name=out,proto3" json:"out,omitempty"`
}

func (x *Case) Reset() {
	*x = Case{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sb_judger_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Case) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Case) ProtoMessage() {}

func (x *Case) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sb_judger_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Case.ProtoReflect.Descriptor instead.
func (*Case) Descriptor() ([]byte, []int) {
	return file_rpc_sb_judger_proto_rawDescGZIP(), []int{5}
}

func (x *Case) GetCaseId() uint32 {
	if x != nil {
		return x.CaseId
	}
	return 0
}

func (x *Case) GetIn() string {
	if x != nil {
		return x.In
	}
	return ""
}

func (x *Case) GetOut() string {
	if x != nil {
		return x.Out
	}
	return ""
}

type Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaseId        uint32 `protobuf:"varint,1,opt,name=case_id,json=caseId,proto3" json:"case_id,omitempty"`
	CpuTimeUsage  uint32 `protobuf:"varint,2,opt,name=cpu_time_usage,json=cpuTimeUsage,proto3" json:"cpu_time_usage,omitempty"`
	RealTimeUsage uint32 `protobuf:"varint,3,opt,name=real_time_usage,json=realTimeUsage,proto3" json:"real_time_usage,omitempty"`
	MemoryUsage   uint32 `protobuf:"varint,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	State         State  `protobuf:"varint,5,opt,name=state,proto3,enum=v1.judger.State" json:"state,omitempty"`
	OutPut        string `protobuf:"bytes,6,opt,name=out_put,json=outPut,proto3" json:"out_put,omitempty"`
}

func (x *Output) Reset() {
	*x = Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sb_judger_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sb_judger_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_rpc_sb_judger_proto_rawDescGZIP(), []int{6}
}

func (x *Output) GetCaseId() uint32 {
	if x != nil {
		return x.CaseId
	}
	return 0
}

func (x *Output) GetCpuTimeUsage() uint32 {
	if x != nil {
		return x.CpuTimeUsage
	}
	return 0
}

func (x *Output) GetRealTimeUsage() uint32 {
	if x != nil {
		return x.RealTimeUsage
	}
	return 0
}

func (x *Output) GetMemoryUsage() uint32 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *Output) GetState() State {
	if x != nil {
		return x.State
	}
	return State_CE
}

func (x *Output) GetOutPut() string {
	if x != nil {
		return x.OutPut
	}
	return ""
}

type CollectOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaseOuts []*Output `protobuf:"bytes,1,rep,name=case_outs,json=caseOuts,proto3" json:"case_outs,omitempty"`
}

func (x *CollectOutput) Reset() {
	*x = CollectOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sb_judger_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollectOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectOutput) ProtoMessage() {}

func (x *CollectOutput) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sb_judger_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectOutput.ProtoReflect.Descriptor instead.
func (*CollectOutput) Descriptor() ([]byte, []int) {
	return file_rpc_sb_judger_proto_rawDescGZIP(), []int{7}
}

func (x *CollectOutput) GetCaseOuts() []*Output {
	if x != nil {
		return x.CaseOuts
	}
	return nil
}

var File_rpc_sb_judger_proto protoreflect.FileDescriptor

var file_rpc_sb_judger_proto_rawDesc = []byte{
	0x0a, 0x13, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x62, 0x2d, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x76, 0x31, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72,
	0x22, 0xb3, 0x01, 0x0a, 0x0e, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x4c, 0x61,
	0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x12, 0x22, 0x0a, 0x0d, 0x6f, 0x75, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x4d, 0x73,
	0x67, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xc3, 0x01, 0x0a, 0x0f, 0x52, 0x75, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x75,
	0x74, 0x5f, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74,
	0x50, 0x75, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x70, 0x75, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x63, 0x70, 0x75,
	0x54, 0x69, 0x6d, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x61,
	0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0d, 0x72, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x75, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x55,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0xbe, 0x01, 0x0a,
	0x0a, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x61,
	0x73, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x70, 0x75, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x63, 0x70,
	0x75, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65,
	0x61, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0d, 0x72, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x75, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0xc4, 0x01,
	0x0a, 0x10, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x4c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x52, 0x04, 0x6c, 0x61, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x22, 0x0a, 0x0d, 0x6f,
	0x75, 0x74, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x6f, 0x75, 0x74, 0x4d, 0x73, 0x67, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x23, 0x0a, 0x04, 0x63, 0x61, 0x73, 0x65, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x76, 0x31, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x52, 0x04,
	0x63, 0x61, 0x73, 0x65, 0x22, 0xde, 0x01, 0x0a, 0x11, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x76, 0x31, 0x2e, 0x6a,
	0x75, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x6d, 0x61, 0x78, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x6d, 0x61, 0x78, 0x54,
	0x69, 0x6d, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x61, 0x78, 0x5f,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0e, 0x6d, 0x61, 0x78, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x5f, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x50, 0x75, 0x74, 0x12, 0x38, 0x0a, 0x0c, 0x63,
	0x6f, 0x64, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x41, 0x0a, 0x04, 0x43, 0x61, 0x73, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x63, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x75, 0x74, 0x22, 0xd3, 0x01, 0x0a, 0x06, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x61, 0x73, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e,
	0x63, 0x70, 0x75, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x70, 0x75, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x72, 0x65, 0x61,
	0x6c, 0x54, 0x69, 0x6d, 0x65, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0b, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x55, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x76,
	0x31, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x75, 0x74, 0x5f, 0x70, 0x75, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x50, 0x75, 0x74, 0x22, 0x3f,
	0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x2e, 0x0a, 0x09, 0x63, 0x61, 0x73, 0x65, 0x5f, 0x6f, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x76, 0x31, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x08, 0x63, 0x61, 0x73, 0x65, 0x4f, 0x75, 0x74, 0x73, 0x2a,
	0x46, 0x0a, 0x08, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x05, 0x0a, 0x01, 0x63,
	0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x63, 0x70, 0x70, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x67,
	0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x6a, 0x61, 0x76, 0x61, 0x10,
	0x03, 0x12, 0x0a, 0x0a, 0x06, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x10, 0x04, 0x12, 0x08, 0x0a,
	0x04, 0x72, 0x75, 0x73, 0x74, 0x10, 0x05, 0x2a, 0x41, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x06, 0x0a, 0x02, 0x43, 0x45, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x41, 0x43, 0x10, 0x01,
	0x12, 0x06, 0x0a, 0x02, 0x57, 0x41, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02, 0x52, 0x45, 0x10, 0x03,
	0x12, 0x07, 0x0a, 0x03, 0x54, 0x4c, 0x45, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x4c, 0x45,
	0x10, 0x05, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x45, 0x10, 0x06, 0x32, 0x90, 0x01, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19,
	0x2e, 0x76, 0x31, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x52, 0x75, 0x6e, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x6a,
	0x75, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x09, 0x4a, 0x75, 0x64, 0x67, 0x65, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x1b, 0x2e, 0x76, 0x31, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x4a,
	0x75, 0x64, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x76, 0x31, 0x2e, 0x6a, 0x75, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x4a, 0x75, 0x64, 0x67,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x73, 0x62, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_sb_judger_proto_rawDescOnce sync.Once
	file_rpc_sb_judger_proto_rawDescData = file_rpc_sb_judger_proto_rawDesc
)

func file_rpc_sb_judger_proto_rawDescGZIP() []byte {
	file_rpc_sb_judger_proto_rawDescOnce.Do(func() {
		file_rpc_sb_judger_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_sb_judger_proto_rawDescData)
	})
	return file_rpc_sb_judger_proto_rawDescData
}

var file_rpc_sb_judger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rpc_sb_judger_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rpc_sb_judger_proto_goTypes = []interface{}{
	(Language)(0),             // 0: v1.judger.Language
	(State)(0),                // 1: v1.judger.State
	(*RunCodeRequest)(nil),    // 2: v1.judger.RunCodeRequest
	(*RunCodeResponse)(nil),   // 3: v1.judger.RunCodeResponse
	(*CodeResult)(nil),        // 4: v1.judger.CodeResult
	(*JudgeCodeRequest)(nil),  // 5: v1.judger.JudgeCodeRequest
	(*JudgeCodeResponse)(nil), // 6: v1.judger.JudgeCodeResponse
	(*Case)(nil),              // 7: v1.judger.Case
	(*Output)(nil),            // 8: v1.judger.Output
	(*CollectOutput)(nil),     // 9: v1.judger.CollectOutput
}
var file_rpc_sb_judger_proto_depIdxs = []int32{
	0,  // 0: v1.judger.RunCodeRequest.lang:type_name -> v1.judger.Language
	1,  // 1: v1.judger.RunCodeResponse.state:type_name -> v1.judger.State
	1,  // 2: v1.judger.CodeResult.state:type_name -> v1.judger.State
	0,  // 3: v1.judger.JudgeCodeRequest.lang:type_name -> v1.judger.Language
	7,  // 4: v1.judger.JudgeCodeRequest.case:type_name -> v1.judger.Case
	1,  // 5: v1.judger.JudgeCodeResponse.state:type_name -> v1.judger.State
	4,  // 6: v1.judger.JudgeCodeResponse.code_results:type_name -> v1.judger.CodeResult
	1,  // 7: v1.judger.Output.state:type_name -> v1.judger.State
	8,  // 8: v1.judger.CollectOutput.case_outs:type_name -> v1.judger.Output
	2,  // 9: v1.judger.Code.RunCode:input_type -> v1.judger.RunCodeRequest
	5,  // 10: v1.judger.Code.JudgeCode:input_type -> v1.judger.JudgeCodeRequest
	3,  // 11: v1.judger.Code.RunCode:output_type -> v1.judger.RunCodeResponse
	6,  // 12: v1.judger.Code.JudgeCode:output_type -> v1.judger.JudgeCodeResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_rpc_sb_judger_proto_init() }
func file_rpc_sb_judger_proto_init() {
	if File_rpc_sb_judger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_sb_judger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sb_judger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sb_judger_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sb_judger_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JudgeCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sb_judger_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JudgeCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sb_judger_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Case); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sb_judger_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sb_judger_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollectOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_sb_judger_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_sb_judger_proto_goTypes,
		DependencyIndexes: file_rpc_sb_judger_proto_depIdxs,
		EnumInfos:         file_rpc_sb_judger_proto_enumTypes,
		MessageInfos:      file_rpc_sb_judger_proto_msgTypes,
	}.Build()
	File_rpc_sb_judger_proto = out.File
	file_rpc_sb_judger_proto_rawDesc = nil
	file_rpc_sb_judger_proto_goTypes = nil
	file_rpc_sb_judger_proto_depIdxs = nil
}
